### ISSUE TITLE
Provide organisation.json sample data 

### ISSUE THREAD

**Issue by manga1** [sugarso/mappedinisrael#1]
Hi!

I'm new to xcode im learning for a 6 months objective-c and im learning a lot. I stumbled on your project and it is amazing... It's a great learning tool... the app works perfect hands down guy's... but I would be very greatfull if you'd put the file in to see the whole structure of the organisation.json file so some can take examples.

Thank you!

**Comment by maximveksler** [comment]
@genadyo can we put a sample of the data? Perhaps Iris Shoor & Sugar studio?

**Comment by manga1** [comment]
Yes it would be great! Thank you!
